---
title: "Data Processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#import raw data
data <- read.csv("../data/Housing_Litigations.csv", header = T)
```

```{r}
#change date format
library(anytime)
data$CaseOpenDate<- anydate(data$CaseOpenDate)
```

```{r}
#clean casestatus
ca <- strsplit(sapply(data$CaseStatus, as.character), split=" ")
ca <- lapply(ca, "[[", 1)
data$CaseStatus <- unlist(ca)
data$CaseStatus[data$CaseStatus == "Exempt-"] <- "Exempt"
data$CaseStatus[data$CaseStatus == "WithDrawn/Abandoned-"] <- "WithDrawn/Abandoned"
data$CaseStatus[data$CaseStatus == "Rescinded-"] <- "Rescinded"
data$CaseStatus[data$CaseStatus == "Rejected-"] <- "Rejected"
```

```{r}
#transfer na to 0 for penalty
data$Penalty[is.na(data$Penalty)] <- 0
```

```{r}
#export data
data <- na.omit(data)
save(data, file="../output/processed_data.Rdata")

building <- data %>% group_by(BuildingID) %>% tally()
geo <- data %>% dplyr::select(BuildingID, Latitude, Longitude, StreetName, HouseNumber, Respondent)
building_geo <- left_join(lit_building, lit_geo, by = "BuildingID")
save(building_geo, file="../output/building_geo.RData")
```

