---
title: "ADS Project2"
author: "NAN YANG"
date: "10/2/2019"
output: html_document
---
```{r}
library(rgdal)
library(leaflet)
library(shiny)
library(dplyr)
library(raster)
library(tigris)
library(sp)
library(ggmap)
library(maptools)
library(broom)
library(httr)
```

```{r}
data1<-read.csv("../data/processed_data.csv")
under <- readOGR("../data/ZIP_CODE_040114.shp")
```

```{r}
ui <- fluidPage(
  h1("Map of Frequences"),
  sidebarLayout(
    sidebarPanel(
       selectInput("Zip_frequence", "Case:",
                   c("Comprehensive" = "Comprehensive",
                     "Heat and Hot Water" = "Heat and Hot Water",
                    "Access Warrant - Non-Lead" = "Access Warrant - Non-Lead",
                    "Tenant Action" = "Tenant Action",
                    "False Certification Non-Lead" = "False Certification Non-Lead",
                    "Heat Supplemental Cases" = "Heat Supplemental Cases",
                    "Tenant Action/Harrassment" = "Tenant Action/Harrassment",
                    "CONH" = "CONH",
                    "Access Warrant - lead" = "Access Warrant - lead",
                    "Comp Supplemental Cases" = "Comp Supplemental Cases",
                    "Lead False Certification" = "Lead False Certification",
                    "Failure to Register Only" = "Failure to Register Only",
                    "7A" = "7A",
                    "HLD - Other Case Type" = "HLD - Other Case Type"), 
                   selected = "Comprehensive",
                   multiple = TRUE),
       checkboxGroupInput("CaseOpenDate", "Case Open Date:",
                   c("2000" = "2000",
                     "2001" = "2001",
                     "2002" = "2002",
                     "2003" = "2003",
                     "2004" = "2004",
                     "2005" = "2005",
                     "2006" = "2006",
                     "2007" = "2007",
                     "2008" = "2008",
                     "2009" = "2009",
                     "2010" = "2010",
                     "2011" = "2011",
                     "2012" = "2012",
                     "2013" = "2013",
                     "2014" = "2014",
                     "2015" = "2015",
                     "2016" = "2016",
                     "2017" = "2017",
                     "2018" = "2018"), selected = "2018")
       
       
    ),
    mainPanel(
      leafletOutput("mymap1",height = 1000)
    )
  )
)
```

```{r}

server=function(input, output) {
  output$mymap1 <- renderLeaflet({
    data1$CaseOpenDate <- as.Date(data1$CaseOpenDate) %>% format("%Y")
    datasliced<-dplyr::filter(data1, data1$CaseType==input$Zip_frequence, data1$CaseOpenDate==input$CaseOpenDate)
      #data1[data1$CaseType==input$Zip_frequence,]
    
    ZIPCODE<-names(table(datasliced$Zip))
    frequence<-unname(table(datasliced$Zip))
    Zip<-as.data.frame(cbind(ZIPCODE,frequence))
    under1 <- subset(under, is.element(Zip$ZIPCODE, under$ZIPCODE))
    under2 <- subset(under1, is.element(under1$ZIPCODE, Zip$ZIPCODE))
    under2@data = merge(x=under2@data, y=Zip, by = "ZIPCODE", all.x = TRUE)
    subdat1 <- spTransform(under2, CRS("+init=epsg:4326"))
    subdat1@data$frequence <- as.numeric(subdat1@data$frequence)
    
    subdat1$lab <- paste("<p>", "ZIPCODE", subdat1$ZIPCODE, "<p>",
                         "<p>", "Case Frequence", subdat1$frequence, "<p>")
    
    
    pal <- colorNumeric(
       palette = "Blues",
       domain = subdat1$frequence
       )

    m <- leaflet(under) %>%
      addProviderTiles(providers$Stamen.Toner) %>%
      setView(lng = -73.98928, lat = 40.75042, zoom = 12)%>% 
      addPolygons(data = subdat1,
                  weight = 1,
                  smoothFactor = 0.5,
                  color = "white",
                  fillOpacity = 0.8,
                  fillColor = pal(subdat1$frequence),
                  label = lapply(subdat1$lab, HTML),
                  highlight = highlightOptions(weight = 10,
                                       color = "White",
                                       bringToFront = TRUE))})
  }
    
```

```{r}

# Run the app ----
shinyApp(ui = ui, server = server)


```

