---
title: "Tab 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(leaflet)
library(shiny)
library(plotly)

lit <- read.csv("../data/processed_data.csv") %>% na.omit()

lit_building <- lit %>% group_by(BuildingID) %>% tally()
lit_geo <- lit %>% dplyr::select(BuildingID, Latitude, Longitude, StreetName, HouseNumber, Respondent)
lit_building_geo <- left_join(lit_building, lit_geo, by = "BuildingID") %>% distinct()

```

```{r}
ui <- fluidPage(
  
  h1("Litigations of each Building"),
  
  sidebarLayout(
    
    sidebarPanel(
       sliderInput("numlit_t2", "Amount of litigations",  min = min(lit_building$n), max = max(lit_building$n), value = 25 ), 
       actionButton("building_t2","See/Update Building Details"),
       textOutput("describe_t2"),
       br(),
       plotlyOutput("histogram_t2", height = 350),
       br(),
       plotlyOutput("pie_t2", height = 300)
    ),
    
    mainPanel(
      leafletOutput("mymap_t2",height = 800)
    )
    
  )
)
```


```{r}
server <- function(input, output){

   output$mymap_t2 <- renderLeaflet({
     
     data <- filter(lit_building_geo, n>= input$numlit_t2)
     
     m <- leaflet(data = data) %>%
       addTiles() %>%
       setView(lng = -73.9588,
               lat = 40.74 ,
               zoom = 11) %>%
       addProviderTiles("CartoDB.Positron") %>%
       addCircleMarkers(
         lng = ~ Longitude,
         lat = ~ Latitude,
         popup = ~ paste0(
          "Address: ", HouseNumber, " ", StreetName, "<br/>Litigations: " , n, "<br/>Most Recent Respondent: " , Respondent
         ),
         radius = 4,
         color = "lightblue",
         fillColor = "white",
         opacity = 0.5
       )
   })
   
   output$describe_t2 <- renderText({
     paste("Click on map to choose a building, displays info on all buildings if no building selected")
   })
   
   observe({
     posi <<- reactive({
       input$mymap_t2_marker_click
     })
   })

   observeEvent(input$building_t2,{
     
     if(input$building_t2){
       if(is.null(posi())){
         plot_data <- lit
       } else{
          plot_data <- dplyr::filter(lit, Latitude==posi()$lat, Longitude==posi()$lng)}
     
        output$histogram_t2 <- renderPlotly({
     ts_data <- plot_data
     ts_data$CaseOpenDate <-
       as.Date(ts_data$CaseOpenDate) %>% format("%Y")
     ts_data <- group_by(ts_data, CaseOpenDate) %>% tally()
     colnames(ts_data) <- c("Year", "Number of litigation")
     
     ts <- ggplot(ts_data, aes(x = Year, y = `Number of litigation`)) +
       geom_bar(stat = "identity") +
       ggtitle("Amount of Litigations in each year") +
       labs(x = "Years", y = "Number of litigation") +coord_flip()
     ts <- ggplotly(ts)
     ts
   })

   output$pie_t2 <- renderPlotly({
      plot_ly() %>%
       add_pie(
         data = count(plot_data, CaseType),
         labels = ~ CaseType,
         values = ~ n,
         name = "Litigation by case types",
         domain = list(x = c(0, 0.45), y = c(0, 1))
       ) %>%
       add_pie(
         data = count(plot_data, CaseStatus),
         labels = ~ CaseStatus,
         values = ~ n,
         name = "Status of the litigation",
         domain = list(x = c(0.55, 1), y = c(0, 1))
       ) %>%
       layout(
         title = "Litigation details (type and case status)",
         showlegend = F,
         xaxis = list(
           showgrid = FALSE,
           zeroline = FALSE,
           showticklabels = FALSE
         ),
         yaxis = list(
           showgrid = FALSE,
           zeroline = FALSE,
           showticklabels = FALSE
         )
       )
      
   })
   
     }
     
   })

}

shinyApp(ui, server)

```
