
---
title: "Respondent Distribution"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(leaflet)
library(shiny)
library(plotly)

lit <- read.csv("../data/processed_data.csv")
lit_landlord <- lit %>% group_by(BuildingID) %>% tally()
lit_geo <- lit %>% dplyr::select(BuildingID, Latitude, Longitude, StreetName, HouseNumber, Respondent)
lit_landlord_geo <- left_join(lit_landlord, lit_geo, by = "BuildingID")
```



```{r}
ui <- fluidPage(
  
  h1("Litigations of each Building"),
  
  sidebarLayout(
    
    sidebarPanel(
       textInput("text_t3", label = h3("Search"), value = "Enter Respondent"),
       actionButton( "search_t3","Search"),
       br(),
       plotlyOutput("histogram_t3", height = 350)
    ),
    
    mainPanel(
      leafletOutput("mymap_t3",height = 800)
    )
    
  )
)
```


```{r}
server <- function(input, output) {
  
  output$mymap_t3 <- renderLeaflet({
    input$search_t3
    data_t3 <- filter(lit_landlord_geo, Respondent == isolate(input$text_t3))
    m <- leaflet(data = data_t3) %>%
      addTiles() %>%
      setView(lng = -73.9588,
              lat = 40.74 ,
              zoom = 11) %>%
      addProviderTiles("CartoDB.Positron") %>%
      addCircleMarkers(
        lng = ~ Longitude,
        lat = ~ Latitude,
        popup = ~ paste0(
          "Address: ",
          HouseNumber,
          " ",
          StreetName,
          "<br/>Litigations: " ,
          n

        ),
        radius = 4,
        color = "red",
        fillColor = "white",
        opacity = 0.5
      )
  })
  
  
  
  output$histogram_t3 <- renderPlotly({
    input$search_t3
    data_t3 <- filter(lit_landlord_geo, Respondent == isolate(input$text_t3))
    if (nrow(data_t3) == 0) {
      return(NULL)
    }
    
    ts_data_t3 <- group_by(data_t3, BuildingID) %>% count()
    colnames(ts_data_t3) <-
      c("BuildingID", "Number of litigations")
    ts_data_t3 <-
      group_by(ts_data_t3, `Number of litigations`) %>% tally()
    colnames(ts_data_t3) <-
      c("Number of litigations", "Number of buildings")
    
    ts_t3 <-
      ggplot(ts_data_t3,
             aes(x = `Number of litigations`, y = `Number of buildings`)) +
      geom_bar(stat = "identity") +
      ggtitle("Histogram of buildings per litigation number") +
      labs(x = "Number of litigations", y = "Number of buildings") +
      theme(plot.title = element_text(size = 12, face = "bold"))
    ts_t3 <- ggplotly(ts_t3)
    ts_t3
  })
  
}

shinyApp(ui, server)

```

